name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore workloads
      run: dotnet workload restore "mobile/ZapretUI Mobile.csproj"

    - name: Publish
      run: dotnet publish "mobile/ZapretUI Mobile.csproj" -f net9.0-android -c Release -r android-arm64 -o ./artifacts

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zapret-apk
        path: ./artifacts/*.apk
