name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Publish
      run: dotnet publish "mobile/ZapretUI Mobile.csproj" -f net10.0-android -c Release -r android-arm64 -o ./artifacts

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: zapret-apk
        path: ./artifacts/*.apk
