name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Workloads
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore "mobile/ZapretUI Mobile.csproj"

    - name: Publish
      run: dotnet publish "mobile/ZapretUI Mobile.csproj" -f net10.0-android -c Release -r android-arm64 -o ./artifacts

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: zapret
        path: ./artifacts/*.apk
